FROM debian:bullseye-slim
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        bash-completion               \
        ca-certificates               \
        curl                          \
        fzf                           \
        tzdata                        \
        wget                          \
        vim"

RUn set -ex \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES} \
    && echo "no" | dpkg-reconfigure dash \
    && sed -i "s@# export @export @g" ~/.bashrc \
    && sed -i "s@# alias @alias @g" ~/.bashrc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

ARG KUBECTL_VERSION=v1.29.1
ARG K9S_VERSION=v0.31.7
ARG HELM_VERSION=v3.14.0
ARG KUBECTX_VERSION=v0.9.5

RUN set -ex \
    && \
    case $TARGETARCH in \
        amd64) \
            ARCH="x86_64" \
            ;; \
        *) \
            ARCH=$TARGETARCH \
            ;; \
    esac \
    && mkdir -p /opt/kubectl-aliases /opt/webkubectl \
    && wget -qO /usr/local/bin/kubectl https://dl.k8s.io/${KUBECTL_VERSION}/kubernetes-client-linux-${TARGETARCH}.tar.gz \
    && wget -qO /opt/kubectl-aliases/.kubectl_aliases https://github.com/ahmetb/kubectl-aliases/raw/master/.kubectl_aliases \
    && wget -qO /opt/k9s.tar.gz https://github.com/derailed/k9s/releases/download/v0.31.7/k9s_Linux_amd64.tar.gz \
    && tar -xf /opt/k9s.tar.gz -C /usr/local/bin k9s \
    && wget -qO /opt/helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-${TARGETARCH}.tar.gz \
    && tar -xf /opt/helm.tar.gz --strip-components=1 -C /usr/local/bin linux-${TARGETARCH}/helm \
    && wget -qO /opt/kubectx.tar.gz https://github.com/ahmetb/kubectx/releases/download/${KUBECTX_VERSION}/kubectx_${KUBECTX_VERSION}_linux_${ARCH}.tar.gz \
    && tar -xf /opt/kubectx.tar.gz -C /usr/local/bin kubectx \
    && wget -qO /opt/kubens.tar.gz https://github.com/ahmetb/kubectx/releases/download/${KUBECTX_VERSION}/kubens_${KUBECTX_VERSION}_linux_${ARCH}.tar.gz \
    && tar -xf /opt/kubens.tar.gz -C /usr/local/bin kubens \
    && chmod 755 /usr/local/bin/* \
    && chown -R root:root /usr/local/bin/* \
    && rm -f /opt/*.tar.gz /opt/install

ARG VERSION=v1.1.1
ENV VERSION=${VERSION}

RUN set -ex \
    && wget -qO kubepi-server.tar.gz https://github.com/wojiushixiaobai/KubePi/releases/download/${VERSION}/kubepi-server-${VERSION}-linux-${TARGETARCH}.tar.gz \
    && tar -xf kubepi-server.tar.gz -C /usr/local/bin kubepi-server \
    && wget -qO gotty.tar.gz https://github.com/wojiushixiaobai/KubePi/releases/download/${VERSION}/gotty-linux-${TARGETARCH}.tar.gz \
    && tar -xf gotty.tar.gz -C /usr/local/bin gotty \
    && chmod 755 /usr/local/bin/* \
    && chown -R root:root /usr/local/bin/* \
    && rm -f /opt/*.tar.gz

COPY conf/app.yml /etc/kubepi/app.yml
COPY vimrc.local /etc/vim

EXPOSE 80

CMD ["kubepi-server"]